var fonts = [
      "ABeeZee",
      "Abel",
      "Abhaya Libre",
      "Abril Fatface",
      "Aclonica",
      "Acme",
      "Actor",
      "Adamina",
      "Advent Pro",
      "Aguafina Script",
      "Akronim",
      "Aladin",
      "Aldrich",
      "Alef",
      "Alegreya",
      "Alegreya SC",
      "Alegreya Sans",
      "Alegreya Sans SC",
      "Alex Brush",
      "Alfa Slab One",
      "Alice",
      "Alike",
      "Alike Angular",
      "Allan",
      "Allerta",
      "Allerta Stencil",
      "Allura",
      "Almendra",
      "Almendra Display",
      "Almendra SC",
      "Amarante",
      "Amaranth",
      "Amatic SC",
      "Amatica SC",
      "Amethysta",
      "Amiko",
      "Amiri",
      "Amita",
      "Anaheim",
      "Andada",
      "Andika",
      "Angkor",
      "Annie Use Your Telescope",
      "Anonymous Pro",
      "Antic",
      "Antic Didone",
      "Antic Slab",
      "Anton",
      "Arapey",
      "Arbutus",
      "Arbutus Slab",
      "Architects Daughter",
      "Archivo Black",
      "Archivo Narrow",
      "Aref Ruqaa",
      "Arima Madurai",
      "Arimo",
      "Arizonia",
      "Armata",
      "Artifika",
      "Arvo",
      "Arya",
      "Asap",
      "Asar",
      "Asset",
      "Assistant",
      "Astloch",
      "Asul",
      "Athiti",
      "Atma",
      "Atomic Age",
      "Aubrey",
      "Audiowide",
      "Autour One",
      "Average",
      "Average Sans",
      "Averia Gruesa Libre",
      "Averia Libre",
      "Averia Sans Libre",
      "Averia Serif Libre",
      "Bad Script",
      "Baloo",
      "Baloo Bhai",
      "Baloo Bhaina",
      "Baloo Chettan",
      "Baloo Da",
      "Baloo Paaji",
      "Baloo Tamma",
      "Baloo Thambi",
      "Balthazar",
      "Bangers",
      "Basic",
      "Battambang",
      "Baumans",
      "Bayon",
      "Belgrano",
      "Belleza",
      "BenchNine",
      "Bentham",
      "Berkshire Swash",
      "Bevan",
      "Bigelow Rules",
      "Bigshot One",
      "Bilbo",
      "Bilbo Swash Caps",
      "BioRhyme",
      "BioRhyme Expanded",
      "Biryani",
      "Bitter",
      "Black Ops One",
      "Bokor",
      "Bonbon",
      "Boogaloo",
      "Bowlby One",
      "Bowlby One SC",
      "Brawler",
      "Bree Serif",
      "Bubblegum Sans",
      "Bubbler One",
      "Buda",
      "Buenard",
      "Bungee",
      "Bungee Hairline",
      "Bungee Inline",
      "Bungee Outline",
      "Bungee Shade",
      "Butcherman",
      "Butterfly Kids",
      "Cabin",
      "Cabin Condensed",
      "Cabin Sketch",
      "Caesar Dressing",
      "Cagliostro",
      "Cairo",
      "Calligraffitti",
      "Cambay",
      "Cambo",
      "Candal",
      "Cantarell",
      "Cantata One",
      "Cantora One",
      "Capriola",
      "Cardo",
      "Carme",
      "Carrois Gothic",
      "Carrois Gothic SC",
      "Carter One",
      "Catamaran",
      "Caudex",
      "Caveat",
      "Caveat Brush",
      "Cedarville Cursive",
      "Ceviche One",
      "Changa",
      "Changa One",
      "Chango",
      "Chathura",
      "Chau Philomene One",
      "Chela One",
      "Chelsea Market",
      "Chenla",
      "Cherry Cream Soda",
      "Cherry Swash",
      "Chewy",
      "Chicle",
      "Chivo",
      "Chonburi",
      "Cinzel",
      "Cinzel Decorative",
      "Clicker Script",
      "Coda",
      "Coda Caption",
      "Codystar",
      "Coiny",
      "Combo",
      "Comfortaa",
      "Coming Soon",
      "Concert One",
      "Condiment",
      "Content",
      "Contrail One",
      "Convergence",
      "Cookie",
      "Copse",
      "Corben",
      "Cormorant",
      "Cormorant Garamond",
      "Cormorant Infant",
      "Cormorant SC",
      "Cormorant Unicase",
      "Cormorant Upright",
      "Courgette",
      "Cousine",
      "Coustard",
      "Covered By Your Grace",
      "Crafty Girls",
      "Creepster",
      "Crete Round",
      "Crimson Text",
      "Croissant One",
      "Crushed",
      "Cuprum",
      "Cutive",
      "Cutive Mono",
      "Damion",
      "Dancing Script",
      "Dangrek",
      "David Libre",
      "Dawning of a New Day",
      "Days One",
      "Dekko",
      "Delius",
      "Delius Swash Caps",
      "Delius Unicase",
      "Della Respira",
      "Denk One",
      "Devonshire",
      "Dhurjati",
      "Didact Gothic",
      "Diplomata",
      "Diplomata SC",
      "Domine",
      "Donegal One",
      "Doppio One",
      "Dorsa",
      "Dosis",
      "Dr Sugiyama",
      "Droid Sans",
      "Droid Sans Mono",
      "Droid Serif",
      "Duru Sans",
      "Dynalight",
      "EB Garamond",
      "Eagle Lake",
      "Eater",
      "Economica",
      "Eczar",
      "Ek Mukta",
      "El Messiri",
      "Electrolize",
      "Elsie",
      "Elsie Swash Caps",
      "Emblema One",
      "Emilys Candy",
      "Engagement",
      "Englebert",
      "Enriqueta",
      "Erica One",
      "Esteban",
      "Euphoria Script",
      "Ewert",
      "Exo",
      "Exo 2",
      "Expletus Sans",
      "Fanwood Text",
      "Farsan",
      "Fascinate",
      "Fascinate Inline",
      "Faster One",
      "Fasthand",
      "Fauna One",
      "Federant",
      "Federo",
      "Felipa",
      "Fenix",
      "Finger Paint",
      "Fira Mono",
      "Fira Sans",
      "Fjalla One",
      "Fjord One",
      "Flamenco",
      "Flavors",
      "Fondamento",
      "Fontdiner Swanky",
      "Forum",
      "Francois One",
      "Frank Ruhl Libre",
      "Freckle Face",
      "Fredericka the Great",
      "Fredoka One",
      "Freehand",
      "Fresca",
      "Frijole",
      "Fruktur",
      "Fugaz One",
      "GFS Didot",
      "GFS Neohellenic",
      "Gabriela",
      "Gafata",
      "Galada",
      "Galdeano",
      "Galindo",
      "Gentium Basic",
      "Gentium Book Basic",
      "Geo",
      "Geostar",
      "Geostar Fill",
      "Germania One",
      "Gidugu",
      "Gilda Display",
      "Give You Glory",
      "Glass Antiqua",
      "Glegoo",
      "Gloria Hallelujah",
      "Goblin One",
      "Gochi Hand",
      "Gorditas",
      "Goudy Bookletter 1911",
      "Graduate",
      "Grand Hotel",
      "Gravitas One",
      "Great Vibes",
      "Griffy",
      "Gruppo",
      "Gudea",
      "Gurajada",
      "Habibi",
      "Halant",
      "Hammersmith One",
      "Hanalei",
      "Hanalei Fill",
      "Handlee",
      "Hanuman",
      "Happy Monkey",
      "Harmattan",
      "Headland One",
      "Heebo",
      "Henny Penny",
      "Herr Von Muellerhoff",
      "Hind",
      "Hind Guntur",
      "Hind Madurai",
      "Hind Siliguri",
      "Hind Vadodara",
      "Holtwood One SC",
      "Homemade Apple",
      "Homenaje",
      "IM Fell DW Pica",
      "IM Fell DW Pica SC",
      "IM Fell Double Pica",
      "IM Fell Double Pica SC",
      "IM Fell English",
      "IM Fell English SC",
      "IM Fell French Canon",
      "IM Fell French Canon SC",
      "IM Fell Great Primer",
      "IM Fell Great Primer SC",
      "Iceberg",
      "Iceland",
      "Imprima",
      "Inconsolata",
      "Inder",
      "Indie Flower",
      "Inika",
      "Inknut Antiqua",
      "Irish Grover",
      "Istok Web",
      "Italiana",
      "Italianno",
      "Itim",
      "Jacques Francois",
      "Jacques Francois Shadow",
      "Jaldi",
      "Jim Nightshade",
      "Jockey One",
      "Jolly Lodger",
      "Jomhuria",
      "Josefin Sans",
      "Josefin Slab",
      "Joti One",
      "Judson",
      "Julee",
      "Julius Sans One",
      "Junge",
      "Jura",
      "Just Another Hand",
      "Just Me Again Down Here",
      "Kadwa",
      "Kalam",
      "Kameron",
      "Kanit",
      "Kantumruy",
      "Karla",
      "Karma",
      "Katibeh",
      "Kaushan Script",
      "Kavivanar",
      "Kavoon",
      "Kdam Thmor",
      "Keania One",
      "Kelly Slab",
      "Kenia",
      "Khand",
      "Khmer",
      "Khula",
      "Kite One",
      "Knewave",
      "Kotta One",
      "Koulen",
      "Kranky",
      "Kreon",
      "Kristi",
      "Krona One",
      "Kumar One",
      "Kumar One Outline",
      "Kurale",
      "La Belle Aurore",
      "Laila",
      "Lakki Reddy",
      "Lalezar",
      "Lancelot",
      "Lateef",
      "Lato",
      "League Script",
      "Leckerli One",
      "Ledger",
      "Lekton",
      "Lemon",
      "Lemonada",
      "Libre Baskerville",
      "Libre Franklin",
      "Life Savers",
      "Lilita One",
      "Lily Script One",
      "Limelight",
      "Linden Hill",
      "Lobster",
      "Lobster Two",
      "Londrina Outline",
      "Londrina Shadow",
      "Londrina Sketch",
      "Londrina Solid",
      "Lora",
      "Love Ya Like A Sister",
      "Loved by the King",
      "Lovers Quarrel",
      "Luckiest Guy",
      "Lusitana",
      "Lustria",
      "Macondo",
      "Macondo Swash Caps",
      "Mada",
      "Magra",
      "Maiden Orange",
      "Maitree",
      "Mako",
      "Mallanna",
      "Mandali",
      "Marcellus",
      "Marcellus SC",
      "Marck Script",
      "Margarine",
      "Marko One",
      "Marmelad",
      "Martel",
      "Martel Sans",
      "Marvel",
      "Mate",
      "Mate SC",
      "Maven Pro",
      "McLaren",
      "Meddon",
      "MedievalSharp",
      "Medula One",
      "Meera Inimai",
      "Megrim",
      "Meie Script",
      "Merienda",
      "Merienda One",
      "Merriweather",
      "Merriweather Sans",
      "Metal",
      "Metal Mania",
      "Metamorphous",
      "Metrophobic",
      "Michroma",
      "Milonga",
      "Miltonian",
      "Miltonian Tattoo",
      "Miniver",
      "Miriam Libre",
      "Mirza",
      "Miss Fajardose",
      "Mitr",
      "Modak",
      "Modern Antiqua",
      "Mogra",
      "Molengo",
      "Molle",
      "Monda",
      "Monofett",
      "Monoton",
      "Monsieur La Doulaise",
      "Montaga",
      "Montez",
      "Montserrat",
      "Montserrat Alternates",
      "Montserrat Subrayada",
      "Moul",
      "Moulpali",
      "Mountains of Christmas",
      "Mouse Memoirs",
      "Mr Bedfort",
      "Mr Dafoe",
      "Mr De Haviland",
      "Mrs Saint Delafield",
      "Mrs Sheppards",
      "Mukta Vaani",
      "Muli",
      "Mystery Quest",
      "NTR",
      "Neucha",
      "Neuton",
      "New Rocker",
      "News Cycle",
      "Niconne",
      "Nixie One",
      "Nobile",
      "Nokora",
      "Norican",
      "Nosifer",
      "Nothing You Could Do",
      "Noticia Text",
      "Noto Sans",
      "Noto Serif",
      "Nova Cut",
      "Nova Flat",
      "Nova Mono",
      "Nova Oval",
      "Nova Round",
      "Nova Script",
      "Nova Slim",
      "Nova Square",
      "Numans",
      "Nunito",
      "Odor Mean Chey",
      "Offside",
      "Old Standard TT",
      "Oldenburg",
      "Oleo Script",
      "Oleo Script Swash Caps",
      "Open Sans",
      "Open Sans Condensed",
      "Oranienbaum",
      "Orbitron",
      "Oregano",
      "Orienta",
      "Original Surfer",
      "Oswald",
      "Over the Rainbow",
      "Overlock",
      "Overlock SC",
      "Ovo",
      "Oxygen",
      "Oxygen Mono",
      "PT Mono",
      "PT Sans",
      "PT Sans Caption",
      "PT Sans Narrow",
      "PT Serif",
      "PT Serif Caption",
      "Pacifico",
      "Palanquin",
      "Palanquin Dark",
      "Paprika",
      "Parisienne",
      "Passero One",
      "Passion One",
      "Pathway Gothic One",
      "Patrick Hand",
      "Patrick Hand SC",
      "Pattaya",
      "Patua One",
      "Pavanam",
      "Paytone One",
      "Peddana",
      "Peralta",
      "Permanent Marker",
      "Petit Formal Script",
      "Petrona",
      "Philosopher",
      "Piedra",
      "Pinyon Script",
      "Pirata One",
      "Plaster",
      "Play",
      "Playball",
      "Playfair Display",
      "Playfair Display SC",
      "Podkova",
      "Poiret One",
      "Poller One",
      "Poly",
      "Pompiere",
      "Pontano Sans",
      "Poppins",
      "Port Lligat Sans",
      "Port Lligat Slab",
      "Pragati Narrow",
      "Prata",
      "Preahvihear",
      "Press Start 2P",
      "Pridi",
      "Princess Sofia",
      "Prociono",
      "Prompt",
      "Prosto One",
      "Proza Libre",
      "Puritan",
      "Purple Purse",
      "Quando",
      "Quantico",
      "Quattrocento",
      "Quattrocento Sans",
      "Questrial",
      "Quicksand",
      "Quintessential",
      "Qwigley",
      "Racing Sans One",
      "Radley",
      "Rajdhani",
      "Rakkas",
      "Raleway",
      "Raleway Dots",
      "Ramabhadra",
      "Ramaraja",
      "Rambla",
      "Rammetto One",
      "Ranchers",
      "Rancho",
      "Ranga",
      "Rasa",
      "Rationale",
      "Ravi Prakash",
      "Redressed",
      "Reem Kufi",
      "Reenie Beanie",
      "Revalia",
      "Rhodium Libre",
      "Ribeye",
      "Ribeye Marrow",
      "Righteous",
      "Risque",
      "Roboto",
      "Roboto Condensed",
      "Roboto Mono",
      "Roboto Slab",
      "Rochester",
      "Rock Salt",
      "Rokkitt",
      "Romanesco",
      "Ropa Sans",
      "Rosario",
      "Rosarivo",
      "Rouge Script",
      "Rozha One",
      "Rubik",
      "Rubik Mono One",
      "Rubik One",
      "Ruda",
      "Rufina",
      "Ruge Boogie",
      "Ruluko",
      "Rum Raisin",
      "Ruslan Display",
      "Russo One",
      "Ruthie",
      "Rye",
      "Sacramento",
      "Sahitya",
      "Sail",
      "Salsa",
      "Sanchez",
      "Sancreek",
      "Sansita One",
      "Sarala",
      "Sarina",
      "Sarpanch",
      "Satisfy",
      "Scada",
      "Scheherazade",
      "Schoolbell",
      "Scope One",
      "Seaweed Script",
      "Secular One",
      "Sevillana",
      "Seymour One",
      "Shadows Into Light",
      "Shadows Into Light Two",
      "Shanti",
      "Share",
      "Share Tech",
      "Share Tech Mono",
      "Shojumaru",
      "Short Stack",
      "Shrikhand",
      "Siemreap",
      "Sigmar One",
      "Signika",
      "Signika Negative",
      "Simonetta",
      "Sintony",
      "Sirin Stencil",
      "Six Caps",
      "Skranji",
      "Slabo 13px",
      "Slabo 27px",
      "Slackey",
      "Smokum",
      "Smythe",
      "Sniglet",
      "Snippet",
      "Snowburst One",
      "Sofadi One",
      "Sofia",
      "Sonsie One",
      "Sorts Mill Goudy",
      "Source Code Pro",
      "Source Sans Pro",
      "Source Serif Pro",
      "Space Mono",
      "Special Elite",
      "Spicy Rice",
      "Spinnaker",
      "Spirax",
      "Squada One",
      "Sree Krushnadevaraya",
      "Sriracha",
      "Stalemate",
      "Stalinist One",
      "Stardos Stencil",
      "Stint Ultra Condensed",
      "Stint Ultra Expanded",
      "Stoke",
      "Strait",
      "Sue Ellen Francisco",
      "Suez One",
      "Sumana",
      "Sunshiney",
      "Supermercado One",
      "Sura",
      "Suranna",
      "Suravaram",
      "Suwannaphum",
      "Swanky and Moo Moo",
      "Syncopate",
      "Tangerine",
      "Taprom",
      "Tauri",
      "Taviraj",
      "Teko",
      "Telex",
      "Tenali Ramakrishna",
      "Tenor Sans",
      "Text Me One",
      "The Girl Next Door",
      "Tienne",
      "Tillana",
      "Timmana",
      "Tinos",
      "Titan One",
      "Titillium Web",
      "Trade Winds",
      "Trirong",
      "Trocchi",
      "Trochut",
      "Trykker",
      "Tulpen One",
      "Ubuntu",
      "Ubuntu Condensed",
      "Ubuntu Mono",
      "Ultra",
      "Uncial Antiqua",
      "Underdog",
      "Unica One",
      "UnifrakturCook",
      "UnifrakturMaguntia",
      "Unkempt",
      "Unlock",
      "Unna",
      "VT323",
      "Vampiro One",
      "Varela",
      "Varela Round",
      "Vast Shadow",
      "Vesper Libre",
      "Vibur",
      "Vidaloka",
      "Viga",
      "Voces",
      "Volkhov",
      "Vollkorn",
      "Voltaire",
      "Waiting for the Sunrise",
      "Wallpoet",
      "Walter Turncoat",
      "Warnes",
      "Wellfleet",
      "Wendy One",
      "Wire One",
      "Work Sans",
      "Yanone Kaffeesatz",
      "Yantramanav",
      "Yatra One",
      "Yellowtail",
      "Yeseva One",
      "Yesteryear",
      "Yrsa",
      "Zeyada"
    ];
    var template = [
      ':root {',
      '  --color-transparent: {{root-transparent}};',
      '  --color-white: {{message-color}};',
      '  --color-message-text: {{message-text-color}};',
      '  --color-black: {{outline-color}};',
      '  --color-primary: {{author-color}};',
      '  --color-owner: {{author-owner-color}};',
      '  --color-badge-bg: {{badge-background-color}};',
      '  --color-timestamp: {{timestamp-color}};',
      '  --color-owner-badge: {{author-owner-color}};',
      '  --color-moderator-badge: {{author-moderator-color}};',
      '  --color-member-badge: {{author-member-color}};',
      '  --color-channel-name: {{author-color}};',
      '  --color-owner-accent: {{owner-message-background-base}};',
      '  --color-moderator-accent: {{moderator-message-background-base}};',
      '  --color-muted-panel: {{message-background-base}};',
      '  --color-member-light: {{member-message-background-base}};',
      '  --background-owner: {{background-owner}};',
      '  --background-moderator: {{background-moderator}};',
      '  --background-member: {{background-member}};',
      '}',
      '',
      'body {',
      '  overflow: hidden;',
      '  background-color: var(--color-transparent);',
      '}',
      '',
      'yt-live-chat-renderer,',
      'yt-live-chat-text-message-renderer,',
      'yt-live-chat-text-message-renderer[is-highlighted],',
      'yt-live-chat-text-message-renderer[author-type="owner"],',
      'yt-live-chat-text-message-renderer[author-type="owner"][is-highlighted],',
      'yt-live-chat-text-message-renderer[author-type="moderator"],',
      'yt-live-chat-text-message-renderer[author-type="moderator"][is-highlighted],',
      'yt-live-chat-text-message-renderer[author-type="member"],',
      'yt-live-chat-text-message-renderer[author-type="member"][is-highlighted],',
      'yt-live-chat-author-chip #author-name,',
      'yt-live-chat-ticker-renderer {',
      '  background-color: transparent !important;',
      '}',
      '',
      'yt-live-chat-renderer * {',
      '  {{show-outlines}}',
      '  line-height: normal !important;',
      '}',
      '',
      'yt-live-chat-item-list-renderer #items,',
      'yt-live-chat-item-list-renderer #item-scroller {',
      '  overflow: hidden !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #content,',
      'yt-live-chat-legacy-paid-message-renderer #content {',
      '  overflow: initial !important;',
      '  border: {{content-border-size}}px solid {{content-border-color}} !important;',
      '  border-radius: {{content-border-radius}}px !important;',
      '  box-sizing: border-box !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer {',
      '  animation: chat_bounce 0.5s ease-out forwards;',
      '}',
      '',
      'yt-live-chat-text-message-renderer,',
      'yt-live-chat-legacy-paid-message-renderer,',
      'yt-live-chat-paid-message-renderer #header {',
      '  padding-left: 4px !important;',
      '  padding-right: 4px !important;',
      '}',
      '',
      'yt-live-chat-author-badge-renderer {',
      '  background-color: var(--color-badge-bg) !important;',
      '}',
      '',
      'yt-live-chat-author-badge-renderer[type="moderator"],',
      'yt-live-chat-author-badge-renderer[type="member"] {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '}',
      '',
      'yt-live-chat-author-badge-renderer[type="moderator"]::before {',
      '  content: "\\1F6E1\\FE0F";',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-badges {',
      '  {{show-badges}}',
      '  vertical-align: text-top !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-photo img,',
      'yt-live-chat-paid-message-renderer #author-photo img,',
      'yt-live-chat-legacy-paid-message-renderer #author-photo img {',
      '  object-fit: cover !important;',
      '  display: none !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-photo,',
      'yt-live-chat-paid-message-renderer #author-photo,',
      'yt-live-chat-legacy-paid-message-renderer #author-photo,',
      'yt-live-chat-ticker-paid-message-item-renderer #fake-avatar {',
      '  {{show-avatars}}',
      '  background-color: red !important;',
      '  width: {{avatar-size}}px !important;',
      '  height: {{avatar-size}}px !important;',
      '  min-width: {{avatar-size}}px !important;',
      '  border-radius: 50% !important;',
      '  border: {{avatar-border-size}}px solid {{avatar-border-color}} !important;',
      '  padding: {{avatar-padding}}px !important;',
      '  box-sizing: border-box !important;',
      '  margin: {{avatar-margin-top}}px {{avatar-margin-right}}px {{avatar-margin-bottom}}px {{avatar-margin-left}}px !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #timestamp {',
      '  {{show-timestamps}}',
      '  color: var(--color-timestamp) !important;',
      '  line-height: 16px !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-name {',
      '  color: var(--color-channel-name) !important;',
      '  font-family: "{{author-font-family}}" !important;',
      '  font-size: {{author-font-size}}px !important;',
      '  background: var(--color-white);',
      '  background-size: 200% 100%;',
      '  display: inline-block;',
      '  overflow: hidden;',
      '  text-overflow: ellipsis;',
      '  white-space: nowrap;',
      '  line-height: {{author-line-height}} !important;',
      '  padding: {{author-padding}}px !important;',
      '  border: {{author-border-size}}px solid {{author-border-color}} !important;',
      '  border-radius: {{author-border-radius}}px !important;',
      '  margin: {{author-margin-top}}px {{author-margin-right}}px {{author-margin-bottom}}px {{author-margin-left}}px !important;',
      '  box-sizing: border-box !important;',
      '}',
      '{{show-colon}}',
      '',
      'yt-live-chat-text-message-renderer #author-name[type="owner"],',
      'yt-live-chat-text-message-renderer #author-name.owner,',
      'yt-live-chat-text-message-renderer yt-live-chat-author-badge-renderer[type="owner"] {',
      '  color: var(--color-owner-badge) !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-name[type="moderator"],',
      'yt-live-chat-text-message-renderer #author-name.moderator,',
      'yt-live-chat-text-message-renderer yt-live-chat-author-badge-renderer[type="moderator"] {',
      '  color: var(--color-moderator-badge) !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-name[type="member"],',
      'yt-live-chat-text-message-renderer #author-name.member,',
      'yt-live-chat-text-message-renderer yt-live-chat-author-badge-renderer[type="member"] {',
      '  color: var(--color-member-badge) !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #author-name[type="owner"]::before,',
      'yt-live-chat-text-message-renderer #author-name.owner::before {',
      '  display: none !important;',
      '  background-color: transparent !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #message {',
      '  color: var(--color-message-text) !important;',
      '  font-family: "{{message-font-family}}" !important;',
      '  font-size: {{message-font-size}}px !important;',
      '  background: var(--color-white);',
      '  text-align: left;',
      '  white-space: normal !important;',
      '  display: block !important;',
      '  user-select: none;',
      '  line-height: {{message-line-height}} !important;',
      '  letter-spacing: normal !important;',
      '  padding: {{message-padding}}px !important;',
      '  border: {{message-border-size}}px solid {{message-border-color}} !important;',
      '  border-radius: {{message-border-radius}}px !important;',
      '  margin: {{message-margin-top}}px {{message-margin-right}}px {{message-margin-bottom}}px {{message-margin-left}}px !important;',
      '  box-sizing: border-box !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer #message * {',
      '  color: var(--color-message-text) !important;',
      '  font-family: "{{message-font-family}}" !important;',
      '  font-size: {{message-font-size}}px !important;',
      '  line-height: {{message-line-height}} !important;',
      '  letter-spacing: normal !important;',
      '}',
      '{{message-newline}}',
      '',
      'yt-live-chat-text-message-renderer[author-type="owner"] #message,',
      'yt-live-chat-text-message-renderer #author-name[type="owner"],',
      'yt-live-chat-text-message-renderer #author-name.owner {',
      '  background: var(--background-owner);',
      '}',
      '',
      'yt-live-chat-text-message-renderer[author-type="owner"] #message {',
      '  color: var(--color-message-text) !important;',
      '}',
      '',
      'yt-live-chat-text-message-renderer[author-type="moderator"] #message,',
      'yt-live-chat-text-message-renderer #author-name[type="moderator"],',
      'yt-live-chat-text-message-renderer #author-name.moderator {',
      '  background: var(--background-moderator);',
      '}',
      '',
      'yt-live-chat-text-message-renderer[author-type="member"] #message,',
      'yt-live-chat-text-message-renderer #author-name[type="member"],',
      'yt-live-chat-text-message-renderer #author-name.member,',
      'yt-live-chat-text-message-renderer:has(yt-live-chat-author-badge-renderer[type="moderator"]):has(yt-live-chat-author-badge-renderer[type="member"]) #author-name,',
      'yt-live-chat-text-message-renderer:has(yt-live-chat-author-badge-renderer[type="moderator"]):has(yt-live-chat-author-badge-renderer[type="member"]) #message {',
      '  background: var(--background-member);',
      '  background-size: 200% 100%;',
      '  background-position: 0 0;',
      '  animation: shimmer 2s linear infinite;',
      '}',
      '',
      'yt-live-chat-paid-message-renderer #author-name,',
      'yt-live-chat-paid-message-renderer #author-name *,',
      'yt-live-chat-legacy-paid-message-renderer #event-text,',
      'yt-live-chat-legacy-paid-message-renderer #event-text *,',
      'yt-live-chat-paid-message-renderer #purchase-amount,',
      'yt-live-chat-paid-message-renderer #purchase-amount *,',
      'yt-live-chat-legacy-paid-message-renderer #detail-text,',
      'yt-live-chat-legacy-paid-message-renderer #detail-text *,',
      'yt-live-chat-paid-message-renderer #content,',
      'yt-live-chat-paid-message-renderer #content *,',
      'yt-live-chat-ticker-paid-message-item-renderer,',
      'yt-live-chat-ticker-paid-message-item-renderer *,',
      'yt-live-chat-ticker-sponsor-item-renderer,',
      'yt-live-chat-ticker-sponsor-item-renderer * {',
      '  color: var(--color-white) !important;',
      '}',
      '',
      'yt-live-chat-paid-message-renderer,',
      'yt-live-chat-legacy-paid-message-renderer {',
      '  margin: 4px 0 !important;',
      '}',
      '',
      'yt-live-chat-legacy-paid-message-renderer {',
      '  {{show-fan-funding-background}}',
      '}',
      '',
      'yt-live-chat-text-message-renderer a,',
      'yt-live-chat-legacy-paid-message-renderer a {',
      '  text-decoration: none !important;',
      '}',
      '',
      'yt-live-chat-ticker-renderer {',
      '  box-shadow: none !important;',
      '}',
      '{{ticker}}',
      '{{animations}}',
      '',
      'yt-live-chat-item-list-renderer #items yt-live-chat-text-message-renderer:nth-last-of-type(n+4),',
      'yt-live-chat-text-message-renderer[is-deleted],',
      'yt-live-chat-text-message-renderer[is-deleted] *,',
      'yt-live-chat-legacy-paid-message-renderer[is-deleted],',
      'yt-live-chat-header-renderer,',
      'yt-live-chat-message-input-renderer,',
      'yt-live-chat-ticker-renderer,',
      'yt-live-chat-mode-change-message-renderer,',
      'yt-live-chat-viewer-engagement-message-renderer,',
      'yt-live-chat-restricted-participation-renderer,',
      'yt-live-chat-action-panel-renderer,',
      'yt-live-chat-banner-manager,',
      'yt-live-chat-moderation-message-renderer,',
      'yt-live-chat-membership-only-mode-message-renderer,',
      'yt-live-chat-message-prompt-renderer,',
      'yt-live-chat-subscription-message-renderer,',
      'yt-live-chat-pinned-message-renderer,',
      'yt-live-chat-paid-message-renderer,',
      'yt-live-chat-paid-sticker-renderer,',
      'yt-live-chat-legacy-paid-message-renderer,',
      'yt-live-chat-legacy-paid-sticker-renderer,',
      'yt-reaction-control-panel-overlay,',
      'yt-reaction-control-panel-overlay-view-model,',
      'yt-reaction-control-panel-view-model,',
      'yt-live-chat-renderer #action-panel,',
      'yt-live-chat-renderer #input,',
      'yt-live-chat-text-message-renderer yt-icon,',
      'yt-live-chat-text-message-renderer yt-live-chat-author-chip-renderer,',
      'yt-button-view-model {',
      '  display: none !important;',
      '}',
      '',
      '@keyframes chat_bounce {',
      '  0% {',
      '    transform: translateY(20px);',
      '    opacity: 0;',
      '  }',
      '',
      '  60% {',
      '    transform: translateY(-5px);',
      '    opacity: 1;',
      '  }',
      '',
      '  100% {',
      '    transform: translateY(0);',
      '    opacity: 1;',
      '  }',
      '}',
      '',
      '@keyframes shimmer {',
      '  0% {',
      '    background-position: 100% 0;',
      '  }',
      '',
      '  100% {',
      '    background-position: -100% 0;',
      '  }',
      '}',
    ].join('\n');    var mustacheRegex = /{{(.*?)}}/g;
    var currentValues = {};
    var getValue = function(id) {
      if (Object.prototype.hasOwnProperty.call(currentValues, id)) {
        return currentValues[id];
      }
      return id;
    }
    var isChecked = function(id) {
      return !!currentValues[id];
    }
    var textShadow = function(x, y) {
      return x + 'px ' + y + 'px var(--color-black)';
    };
    var callbacks = {
      'show-outlines': function(id) {
        if (isChecked(id)) {
          var size = getValue('outline-size');
          if (size == 0) {
            return '';
          }
          var color = getValue('outline-color');
          shadow = [];
          for (var x = -size; x <= size; x+=Math.ceil(size/4)) {
            for (var y = -size; y <= size; y+=Math.ceil(size/4)) {
              shadow.push(textShadow(x, y))
            }
          }
          return 'text-shadow: ' + shadow.join(',') + ';';
        }
        return '';
      },
      'show-avatars': function(id) {
        if (!isChecked(id)) {
          return 'display: none !important;'
        }
        return '';
      },
      'show-timestamps': function(id) {
        if (isChecked(id)) {
          return 'display: inline !important;'
        }
        return '';
      },
      'show-badges': function(id) {
        if (!isChecked(id)) {
          return 'display: none !important;';
        }
        return '';
      },
      'show-colon': function(id) {
        if (isChecked(id)) {
          return [
            '',
            'yt-live-chat-text-message-renderer #author-name::after {',
            '  content: ":" !important;',
            '  margin-left: ' + getValue('outline-size') + 'px;',
            '}',
          ].join('\n');
        }
        return [
          '',
          'yt-live-chat-text-message-renderer #author-name::after {',
          '  content: none !important;',
          '  display: none !important;',
          '}',
        ].join('\n');
      },
      'author-line-height': function(id) {
        var value = getValue(id);
        return Number(value) === 0 ? '20px' : value + 'px';
      },
      'message-line-height': function(id) {
        var value = getValue(id);
        return Number(value) === 0 ? 'normal' : value + 'px';
      },
      'message-newline': function(id) {
        if (isChecked(id)) {
          return [
            '',
            'yt-live-chat-text-message-renderer #message {',
            '  display: block !important;',
            '}',
          ].join('\n');
        }
        return '';
      },
      'show-fan-funding-background': function(id) {
        if (isChecked(id)) {
          return [
            'background-color: var(--color-member-badge) !important;',
            '  margin: 4px 0 !important;',
          ].join('\n');
        } else {
          return [
            'background-color: transparent !important;',
            '  box-shadow: none !important;',
            '  margin: 0 !important;',
          ].join('\n');
        }
      },
      'background-color': function() {
        return 'background-color: ' + getColorWithAlpha(getValue('background-color'), getValue('background-opacity')) + ';';
      },
      'root-transparent': function() {
        return getColorWithAlpha(getValue('background-color'), getValue('background-opacity'));
      },
      'badge-background-color': function() {
        return '#f2f2f2';
      },
      'message-background-base': function() {
        return getValue('message-background-color');
      },
      'owner-message-background-base': function() {
        return getValue('owner-message-background-color');
      },
      'moderator-message-background-base': function() {
        return getValue('moderator-message-background-color');
      },
      'member-message-background-base': function() {
        return getValue('member-message-background-color');
      },
      'background-owner': function() {
        if (isChecked('use-gradient-backgrounds')) {
          return 'linear-gradient(to right, var(--color-white), var(--color-owner-accent))';
        }
        return 'var(--color-owner-accent)';
      },
      'background-moderator': function() {
        if (isChecked('use-gradient-backgrounds')) {
          return 'linear-gradient(to right, var(--color-moderator-accent), var(--color-muted-panel))';
        }
        return 'var(--color-moderator-accent)';
      },
      'background-member': function() {
        if (isChecked('use-gradient-backgrounds')) {
          return 'linear-gradient(to right, var(--color-member-light) 25%, var(--color-white) 75%, var(--color-member-light) 100%)';
        }
        return 'var(--color-member-light)';
      },
      'ticker': function() {
        var ret = ''
        if (!isChecked('show-ticker')) {
          ret += [
            'yt-live-chat-ticker-renderer {',
            '  display: none !important;',
            '}',
            '',
          ].join('\n');
        }
        if (!isChecked('show-everything')) {
          ret += [
            'yt-live-chat-item-list-renderer {',
            '  display: none !important;',
            '}',
            '',
          ].join('\n');
        }
        return ret;
      },
      'animations': function() {
        var ain = isChecked('animation-in');
        var aout = isChecked('animation-out');
        if (!ain && !aout) {
          return '';
        }

        var inTime = Number(getValue('animation-in-time'))
        var waitTime = Number(getValue('animation-wait-time')) * 1000
        var outTime = Number(getValue('animation-out-time'))

        var time = 0;
        if (ain) {
          time += inTime;
        }

        if (aout) {
          time += waitTime;
          time += outTime;
        }

        var keyframes = [];
        var runningTime = 0;

        if (ain) {
          keyframes.push('0% { ' + inStyle() + ' }')
          runningTime += inTime;
          keyframes.push(((runningTime/time) * 100) + '% { opacity: 1; transform: none;}')
        }

        if (aout) {
          runningTime += waitTime;
          keyframes.push(((runningTime/time) * 100) + '% { opacity: 1; transform: none;}')
          runningTime += outTime;
          keyframes.push(((runningTime/time) * 100) + '% { ' + outStyle() + ' }')
        }

        return [
          '@keyframes anim {',
          keyframes.join('\n'),
          '}',
          '',
          'yt-live-chat-text-message-renderer,',
          'yt-live-chat-legacy-paid-message-renderer {',
          '  animation: anim ' + time + 'ms;',
          '  animation-fill-mode: forwards;',
          '}',
          ''
        ].join('\n');
      },
    }
    var slide = function(scalar) {
      return (isChecked('animation-reverse') ? -16 : 16) * scalar;
    }
    var inStyle = function() {
      var style = 'opacity: 0;';
      if (isChecked('animation-slide')) {
        style += ' transform: translateX(' + slide(-1) + 'px);'
      }
      return style;
    }
    var outStyle = function() {
      var style = 'opacity: 0;';
      if (isChecked('animation-slide')) {
        style += ' transform: translateX(' + slide(1) + 'px);'
      }
      return style;
    }
    var getColorWithAlpha = function(color, opacity) {
      var c = color.substring(1)
      return 'rgba(' + parseInt(c.substring(0, 2), 16) + ',' + parseInt(c.substring(2, 4), 16) + ',' + parseInt(c.substring(4, 6), 16) + ',' + opacity + ')'
    }
    var generateStyle = function(values) {
      currentValues = values;
      return template.replace(mustacheRegex, function(match) {
        var id = match.substring(2, match.length - 2);
        if (callbacks[id]) {
          return callbacks[id](id);
        }
        return getValue(id);
      });
    }

    var fields = [
      {
        title: 'Fonts',
        controls: [
          { id: 'show-outlines', label: 'Show outlines', type: 'checkbox', checked: true },
          { id: 'outline-size', label: 'Outline size', type: 'number', value: '0' },
          { id: 'outline-color', label: 'Outline color', type: 'color', value: '#000000' },
        ],
      },
      {
        title: 'Avatars',
        controls: [
          { id: 'show-avatars', label: 'Show avatars', type: 'checkbox', checked: true },
          { id: 'avatar-size', label: 'Avatar size', type: 'number', value: '24' },
          { id: 'avatar-padding', label: 'Avatar padding', type: 'number', value: '0' },
          { id: 'avatar-border-size', label: 'Avatar border size', type: 'number', value: '0' },
          { id: 'avatar-border-color', label: 'Avatar border color', type: 'color', value: '#ffffff' },
          { id: 'avatar-margin-top', label: 'Avatar margin top', type: 'number', value: '0' },
          { id: 'avatar-margin-right', label: 'Avatar margin right', type: 'number', value: '6' },
          { id: 'avatar-margin-bottom', label: 'Avatar margin bottom', type: 'number', value: '0' },
          { id: 'avatar-margin-left', label: 'Avatar margin left', type: 'number', value: '0' },
        ],
      },
      {
        title: 'Channel names',
        controls: [
          { id: 'author-font-family', label: 'Font', type: 'select', value: 'Changa One' },
          { id: 'author-font-size', label: 'Font size', type: 'number', value: '20' },
          { id: 'author-line-height', label: 'Line height (0 for default)', type: 'number', value: '0' },
          { id: 'author-color', label: 'Color', type: 'color', value: '#cccccc' },
          { id: 'author-padding', label: 'Padding', type: 'number', value: '0' },
          { id: 'author-border-size', label: 'Border size', type: 'number', value: '0' },
          { id: 'author-border-color', label: 'Border color', type: 'color', value: '#ffffff' },
          { id: 'author-border-radius', label: 'Border radius', type: 'number', value: '0' },
          { id: 'author-margin-top', label: 'Margin top', type: 'number', value: '0' },
          { id: 'author-margin-right', label: 'Margin right', type: 'number', value: '0' },
          { id: 'author-margin-bottom', label: 'Margin bottom', type: 'number', value: '0' },
          { id: 'author-margin-left', label: 'Margin left', type: 'number', value: '0' },
          { id: 'author-owner-color', label: 'Owner color', type: 'color', value: '#ffd600' },
          { id: 'author-moderator-color', label: 'Moderator color', type: 'color', value: '#5e84f1' },
          { id: 'author-member-color', label: 'Sponsor color', type: 'color', value: '#0f9d58' },
          { id: 'show-badges', label: 'Show badges', type: 'checkbox', checked: false },
          { id: 'show-colon', label: 'Show colon after name', type: 'checkbox', checked: true },
        ],
      },
      {
        title: 'Messages',
        controls: [
          { id: 'message-font-family', label: 'Font', type: 'select', value: 'Imprima' },
          { id: 'message-font-size', label: 'Font size', type: 'number', value: '18' },
          { id: 'message-line-height', label: 'Line height', type: 'number', value: '0' },
          { id: 'message-letter-spacing', label: 'Letter spacing', type: 'number', value: '0' },
          { id: 'message-color', label: 'Color', type: 'color', value: '#ffffff' },
          { id: 'message-text-color', label: 'Message text color', type: 'color', value: '#ffffff' },
          { id: 'message-newline', label: 'On new line', type: 'checkbox', checked: false },
          { id: 'message-padding', label: 'Message padding', type: 'number', value: '0' },
          { id: 'message-border-size', label: 'Message border size', type: 'number', value: '0' },
          { id: 'message-border-color', label: 'Message border color', type: 'color', value: '#ffffff' },
          { id: 'message-border-radius', label: 'Message border radius', type: 'number', value: '0' },
          { id: 'message-margin-top', label: 'Message margin top', type: 'number', value: '0' },
          { id: 'message-margin-right', label: 'Message margin right', type: 'number', value: '0' },
          { id: 'message-margin-bottom', label: 'Message margin bottom', type: 'number', value: '0' },
          { id: 'message-margin-left', label: 'Message margin left', type: 'number', value: '0' },
          { id: 'content-border-size', label: 'Content border size', type: 'number', value: '0' },
          { id: 'content-border-color', label: 'Content border color', type: 'color', value: '#ffffff' },
          { id: 'content-border-radius', label: 'Content border radius', type: 'number', value: '0' },
        ],
      },
      {
        title: 'Timestamps',
        controls: [
          { id: 'show-timestamps', label: 'Show timestamps', type: 'checkbox', checked: false },
          { id: 'timestamp-font-family', label: 'Font', type: 'select', value: 'Imprima' },
          { id: 'timestamp-font-size', label: 'Font size', type: 'number', value: '16' },
          { id: 'timestamp-line-height', label: 'Line height (0 for default)', type: 'number', value: '0' },
          { id: 'timestamp-color', label: 'Color', type: 'color', value: '#999999' },
        ],
      },
      {
        title: 'Backgrounds',
        controls: [
          { id: 'background-color', label: 'Background color', type: 'color-range', value: '#000000', rangeId: 'background-opacity', rangeValue: '0' },
          { id: 'use-gradient-backgrounds', label: 'Use gradient backgrounds', type: 'checkbox', checked: true },
          { id: 'message-background-color', label: 'Message background color', type: 'color-range', value: '#cccccc', rangeId: 'message-background-opacity', rangeValue: '0' },
          { id: 'owner-message-background-color', label: 'Owner message background color', type: 'color-range', value: '#ffd600', rangeId: 'owner-message-background-opacity', rangeValue: '0' },
          { id: 'moderator-message-background-color', label: 'Moderator message background color', type: 'color-range', value: '#5e84f1', rangeId: 'moderator-message-background-opacity', rangeValue: '0' },
          { id: 'member-message-background-color', label: 'Sponsor message background color', type: 'color-range', value: '#0f9d58', rangeId: 'member-message-background-opacity', rangeValue: '0' },
        ],
      },
      {
        title: 'SuperChat/Fan Funding/Sponsors',
        controls: [
          { id: 'fan-funding-first-line-font-family', label: 'First line font', type: 'select', value: 'Changa One' },
          { id: 'fan-funding-first-line-font-size', label: 'First line font size', type: 'number', value: '20' },
          { id: 'fan-funding-first-line-line-height', label: 'First line line height (0 for default)', type: 'number', value: '0' },
          { id: 'fan-funding-first-line-color', label: 'First line color', type: 'color', value: '#ffffff' },
          { id: 'fan-funding-second-line-font-family', label: 'Second line font', type: 'select', value: 'Imprima' },
          { id: 'fan-funding-second-line-font-size', label: 'Second line font size', type: 'number', value: '18' },
          { id: 'fan-funding-second-line-line-height', label: 'Second line line height (0 for default)', type: 'number', value: '0' },
          { id: 'fan-funding-second-line-color', label: 'Second line color', type: 'color', value: '#ffffff' },
          { id: 'super-chat-content-font-family', label: 'SuperChat content font', type: 'select', value: 'Imprima' },
          { id: 'super-chat-content-font-size', label: 'SuperChat content font size', type: 'number', value: '18' },
          { id: 'super-chat-content-line-height', label: 'SuperChat content line height (0 for default)', type: 'number', value: '0' },
          { id: 'super-chat-content-color', label: 'SuperChat content color', type: 'color', value: '#ffffff' },
          { id: 'show-fan-funding-background', label: 'Show Sponsor/Fan Funding background', type: 'checkbox', checked: true },
          { id: 'show-ticker', label: 'Show SuperChat ticker', type: 'checkbox', checked: false },
          { id: 'show-everything', label: 'Show everything other than SuperChat ticker', type: 'checkbox', checked: true },
        ],
      },
      {
        title: 'Animation',
        controls: [
          { id: 'animation-in', label: 'Animate in', type: 'checkbox', checked: false },
          { id: 'animation-in-time', label: 'Fade in time (milliseconds)', type: 'number', value: '200' },
          { id: 'animation-out', label: 'Animate out (remove old messages)', type: 'checkbox', checked: false },
          { id: 'animation-wait-time', label: 'Wait time (seconds)', type: 'number', value: '30' },
          { id: 'animation-out-time', label: 'Fade out time (milliseconds)', type: 'number', value: '200' },
          { id: 'animation-slide', label: 'Slide', type: 'checkbox', checked: false },
          { id: 'animation-reverse', label: 'Reverse slide', type: 'checkbox', checked: false },
        ],
      },
    ];

    var exampleMarkup = [
      '<yt-live-chat-renderer>',
      '<yt-live-chat-ticker-renderer>',
      '<yt-live-chat-ticker-paid-message-item-renderer style="background-color: rgba(0,184,212,1);"><div id="content"><span id="fake-avatar"></span><span>$5.00</span></div></yt-live-chat-ticker-paid-message-item-renderer>',
      '<yt-live-chat-ticker-paid-message-item-renderer style="background-color: rgba(208,0,0,1);"><div id="content"><span id="fake-avatar"></span><span>$500.00</span></div></yt-live-chat-ticker-paid-message-item-renderer>',
      '</yt-live-chat-ticker-renderer>',
      '<yt-live-chat-item-list-renderer>',
      '<yt-live-chat-text-message-renderer author-type="owner"><div id="author-photo"></div><div id="content"><span id="timestamp">12:00</span><span id="author-badges"><yt-live-chat-author-badge-renderer type="owner"></yt-live-chat-author-badge-renderer></span><span id="author-name" type="owner">iopred</span><span id="message">Lorem ipsum</span></div></yt-live-chat-text-message-renderer>',
      '<yt-live-chat-text-message-renderer author-type="moderator"><div id="author-photo"></div><div id="content"><span id="timestamp">12:00</span><span id="author-badges"><yt-live-chat-author-badge-renderer type="moderator"></yt-live-chat-author-badge-renderer></span><span id="author-name" type="moderator">Barbara</span><span id="message">dolor sit amet</span></div></yt-live-chat-text-message-renderer>',
      '<yt-live-chat-text-message-renderer author-type="member"><div id="author-photo"></div><div id="content"><span id="timestamp">12:00</span><span id="author-badges"><yt-live-chat-author-badge-renderer type="member"></yt-live-chat-author-badge-renderer></span><span id="author-name" type="member">vorporeal</span><span id="message" type="member">ultricies laoreet</span></div></yt-live-chat-text-message-renderer>',
      '<yt-live-chat-text-message-renderer><div id="author-photo"></div><div id="content"><span id="timestamp">12:00</span><span id="author-name">Tyeler</span><span id="message">pede dictumst</span></div></yt-live-chat-text-message-renderer>',
      '<yt-live-chat-legacy-paid-message-renderer><div id="author-photo"></div><div id="content"><div id="event-text">NEW SPONSOR!</div><div id="detail-text">Welcome <span class="mention">Sunlis</span>!</div></div></yt-live-chat-legacy-paid-message-renderer>',
      '<yt-live-chat-text-message-renderer><div id="author-photo"></div><div id="content"><span id="timestamp">12:00</span><span id="author-name">kevin</span><span id="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span></div></yt-live-chat-text-message-renderer>',
      '<yt-live-chat-legacy-paid-message-renderer><div id="author-photo"></div><div id="content"><div id="event-text">$10.00 from _milktea!</div><div id="detail-text">quis nostrud exercitation ullamco laboris</div></div></yt-live-chat-legacy-paid-message-renderer>',
      '<yt-live-chat-paid-message-renderer><div id="header" style="background-color: rgba(208,0,0,1);"><div id="author-photo"></div><div id="header-content"><div id="author-name">iopred</div><div id="purchase-amount">$500.00</div></div></div><div id="content" style="background-color: rgba(230,33,23,1);"><div id="message" dir="auto">labore est nostrud cillum labore in minim in ut ut nostrud</div></div></yt-live-chat-paid-message-renderer>',
      '<yt-live-chat-paid-message-renderer><div id="header" style="background-color: rgba(0,184,212,1);"><div id="author-photo"></div><div id="header-content"><div id="author-name">iopred</div><div id="purchase-amount">$5.00</div></div></div><div id="content" style="background-color: rgba(0,229,255,1);"><div id="message" dir="auto">labore est nostrud cillum labore in minim in ut ut nostrud</div></div></yt-live-chat-paid-message-renderer>',
      '</yt-live-chat-item-list-renderer>',
      '</yt-live-chat-renderer>',
    ].join('');

    var h = React.createElement;

    var initialValues = fields.reduce(function(result, group) {
      group.controls.forEach(function(control) {
        if (control.type === 'checkbox') {
          result[control.id] = !!control.checked;
        } else {
          result[control.id] = control.value || '';
        }
        if (control.type === 'color-range') {
          result[control.rangeId] = control.rangeValue || '0';
        }
      });
      return result;
    }, {});

    function Control(props) {
      var control = props.control;
      var values = props.values;
      var setValue = props.setValue;
      var input;

      if (control.type === 'select') {
        input = h('select', {
          id: control.id,
          value: values[control.id],
          onChange: function(event) { setValue(control.id, event.target.value); },
        }, fonts.map(function(font) {
          return h('option', { key: font, value: font }, font);
        }));
      } else if (control.type === 'checkbox') {
        input = h('input', {
          id: control.id,
          type: 'checkbox',
          checked: !!values[control.id],
          onChange: function(event) { setValue(control.id, event.target.checked); },
        });
      } else if (control.type === 'color-range') {
        input = [
          h('input', {
            key: 'color',
            id: control.id,
            type: 'color',
            value: values[control.id],
            onChange: function(event) { setValue(control.id, event.target.value); },
          }),
          h('input', {
            key: 'range',
            id: control.rangeId,
            type: 'range',
            min: '0',
            max: '1',
            step: '0.01',
            value: values[control.rangeId],
            onChange: function(event) { setValue(control.rangeId, event.target.value); },
          }),
        ];
      } else {
        input = h('input', {
          id: control.id,
          type: control.type,
          value: values[control.id],
          onChange: function(event) { setValue(control.id, event.target.value); },
        });
      }

      return h('div', { key: control.id },
        h('label', { htmlFor: control.id }, control.label + ': '),
        input
      );
    }

    function App() {
      var state = React.useState(initialValues);
      var values = state[0];
      var setValues = state[1];
      var lastChanged = React.useState('');
      var lastChangedId = lastChanged[0];
      var setLastChangedId = lastChanged[1];
      var previewStyleState = React.useState('');
      var previewStyle = previewStyleState[0];
      var setPreviewStyle = previewStyleState[1];
      var animationTickState = React.useState(0);
      var animationTick = animationTickState[0];
      var setAnimationTick = animationTickState[1];

      var cssOutput = React.useMemo(function() {
        return generateStyle(values);
      }, [values]);

      React.useEffect(function() {
        currentValues = values;
        var exampleStyle = cssOutput + '#fakebody {' + callbacks['background-color']() + '}';
        var isAnimationUpdate = lastChangedId.indexOf('animation') !== -1 || animationTick > 0;
        var timeoutId;

        if (isAnimationUpdate) {
          var style = '';
          if (isChecked('animation-in')) {
            style = inStyle();
          }
          setPreviewStyle(exampleStyle + 'yt-live-chat-text-message-renderer, yt-live-chat-legacy-paid-message-renderer { animation: none !important; ' + style + '}');
          timeoutId = window.setTimeout(function() {
            setPreviewStyle(exampleStyle + 'yt-live-chat-text-message-renderer, yt-live-chat-legacy-paid-message-renderer { animation-delay: 200ms; }');
          }, 1);
        } else {
          setPreviewStyle(exampleStyle + 'yt-live-chat-text-message-renderer, yt-live-chat-legacy-paid-message-renderer { animation: none !important; }');
        }

        return function() {
          if (timeoutId) {
            window.clearTimeout(timeoutId);
          }
        };
      }, [cssOutput, values, lastChangedId, animationTick]);

      var setValue = function(id, value) {
        setValues(function(previous) {
          var next = Object.assign({}, previous);
          next[id] = value;
          return next;
        });
        setLastChangedId(id);
      };

      return h(React.Fragment, null,
        h('h2', null, 'Chat live Custom'),
        h('div', { id: 'split' },
          h('div', { id: 'inputs' },
            fields.map(function(group) {
              return h(React.Fragment, { key: group.title },
                h('h3', null, group.title + ':'),
                h('section', null,
                  group.controls.map(function(control) {
                    return h(Control, { key: control.id, control: control, values: values, setValue: setValue });
                  }),
                  group.title === 'Animation' ? h('div', { key: 'play-animation' },
                    h('button', {
                      id: 'animation-trigger',
                      type: 'button',
                      onClick: function() { setAnimationTick(function(value) { return value + 1; }); },
                    }, 'Play animation')
                  ) : null
                )
              );
            })
          ),
          h('div', { id: 'example' },
            h('h3', null, 'Example:'),
            h('div', { id: 'example-container' },
              h('div', { id: 'fakebody', dangerouslySetInnerHTML: { __html: exampleMarkup } })
            )
          )
        ),
        h('h3', null, 'CSS:'),
        h('textarea', { id: 'output', value: cssOutput, readOnly: true }),
        h('style', { id: 'example-styles' }, previewStyle)
      );
    }

    ReactDOM.createRoot(document.getElementById('root')).render(h(App));

